#!/usr/bin/env python

maxSize = 2000

print("""
<!DOCTYPE html>
<html>
 <head>
  <style>
    div.dimension {
      display: none;
      width: 100px;
      height: 60px;
    }
""")

for i in range(maxSize):
  print(
"""
    @media (width: {0}px) {{
      #w{0} {{
        display: inline-block;
        background-image: url("http://dummyimage.com/100x60/000/fff&text={0}&dim=x");
      }}
    }}

    @media (height: {0}px) {{
      #h{0} {{
        display: inline-block;
        background-image: url("http://dummyimage.com/100x60/000/fff&text={0}&dim=y");
      }}
    }}
""".format(i))

print("""
  </style>
 </head>
 <body>
""")

for i in range(maxSize):
  print(
"""
<div id="w{0}" class="dimension"></div>
""".format(i))

print("""
<img src="http://dummyimage.com/60x60/fff/000&text=x"></img>
""")

for i in range(maxSize):
  print(
"""
<div id="h{0}" class="dimension"></div>
""".format(i))

print("""
 </body>
</html>
""")
